# Generated by Django 5.2.7 on 2025-11-30 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='outfit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='CSS icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='garment',
            name='care_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='garment',
            name='material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='garment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='garment',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('all', 'All Seasons')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='garment',
            name='status',
            field=models.CharField(choices=[('clean', 'Clean'), ('dirty', 'Dirty'), ('washing', 'In Laundry'), ('damaged', 'Damaged')], default='clean', max_length=10),
        ),
        migrations.AddField(
            model_name='outfit',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outfit',
            name='last_worn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outfit',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rate 1-5 stars', null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='times_worn',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outfit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='weather',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='garments',
            field=models.ManyToManyField(related_name='outfits', to='api.garment'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='occasion',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('work', 'Work'), ('formal', 'Formal'), ('party', 'Party'), ('date', 'Date'), ('exercise', 'Exercise'), ('travel', 'Travel'), ('special', 'Special Event')], max_length=20),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('all', 'All Seasons')], max_length=10),
        ),
        migrations.CreateModel(
            name='LaundryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wash_date', models.DateField(auto_now_add=True)),
                ('estimated_completion', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.garment')),
            ],
        ),
        migrations.CreateModel(
            name='WearHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_worn', models.DateField(auto_now_add=True)),
                ('occasion', models.CharField(blank=True, max_length=100)),
                ('weather', models.CharField(blank=True, max_length=100)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('garment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.garment')),
                ('outfit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.outfit')),
            ],
            options={
                'ordering': ['-date_worn'],
            },
        ),
    ]
