# Generated by Django 5.2.7 on 2025-12-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_options_alter_outfit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='layout',
            field=models.TextField(blank=True, help_text='JSON string storing garment positions and z-index'),
        ),
    ]
