# Generated by Django 5.2.7 on 2025-12-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging token', max_length=255, null=True),
        ),
    ]
